service: agenda-medica

frameworkVersion: ">=4.0.0"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: offline  # Defina o estágio para 'offline' ou outro nome customizado

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true  # Evita o prefixo do estágio nas rotas
    port: 3000                 # Define a porta

functions:
  getAgendas:
    handler: src/agenda/controller.getAgendas
    events:
      - http:
          path: agendas
          method: get

  createAgendamento:
    handler: src/agendamento/controller.createAgendamento
    events:
      - http:
          path: agendamento
          method: post
